<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Bottledcode\\DurablePhp\\Config\\RethinkDbConfig' => 'get1',
  'Bottledcode\\DurablePhp\\Config\\Config' => 'get2',
);

    protected function get1()
    {
        return $this->resolveFactory(static fn() => new \Bottledcode\DurablePhp\Config\RethinkDbConfig(
            host: getenv('RETHINKDB_HOST') ?: 'localhost',
            username: getenv('RETHINKDB_USER') ?: 'admin',
            password: getenv('RETHINKDB_PASSWORD') ?: '',
            database: getenv('RETHINKDB_DATABASE') ?: 'peers',
        ), 'Bottledcode\\DurablePhp\\Config\\RethinkDbConfig');
    }

    protected function get2()
    {
        return $this->resolveFactory(static fn(\Bottledcode\DurablePhp\Config\RethinkDbConfig $config) => new \Bottledcode\DurablePhp\Config\Config(
            currentPartition: (int) \array_slice(\explode('-', \gethostname()), -1)[0],
            storageConfig: $config,
            totalPartitions: (int) \getenv('TOTAL_PARTITIONS') ?: 3,
            totalWorkers: (int) \getenv('TOTAL_WORKERS') ?: 32,
            bootstrapPath: __FILE__,
            maximumMemoryPerWorker: 128,
            factory: 'make'
        ), 'Bottledcode\\DurablePhp\\Config\\Config');
    }

}
